version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
      - "./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/html"
    ports:
      - "80:80"
    depends_on:
      - php
      - postgres
    networks: 
      - app-network

  php:
    container_name: php
    build: ./docker/php
    image: luizmoratelli/php-fpm
    restart: always
    depends_on:
      - postgres
    volumes:
      - "./app:/var/www/html"
    networks: 
      - app-network
  
  postgres:
    container_name: postgres
    build: ./docker/postgres
    image: luizmoratelli/postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks: 
      - app-network

volumes:
  postgresql-data:

networks: 
  app-network:
    driver: bridge